---
  - name: Install Docker
    become: yes
    yum: name=docker.x86_64

  - name: Start Docker
    become: yes
    service: name=docker state=restarted

  - name: Installing packages
    become: yes
    yum: name=python-setuptools

  - name: Installing docker compose
    become: yes
    pip: name=docker-compose extra_args=--upgrade

  - name: Copy files
    become: yes
    file:
      src: /usr/local/bin/docker-compose
      dest: /usr/bin/docker-compose
      state: link
      force: yes

  - name: create docker group
    group: name=docker state=present

  - name: add ec2-user to docker group
    become: yes
    user: name=ec2-user groups=docker append=yes

  - name: enable docker
    service: name=docker state=restarted

  - name: muda a permissao da pasta /app
    become: yes
    file: path=/app owner=ec2-user group=domain_users recurse=yes
