###
---
- hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks:

  #Git
  - name: Install Git
    apt:
      name: git
      state: latest
      update_cache: yes

  - git_config:
      name: user.email
      value: marcopollivier@gmail.com

  - git_config:
      name: user.name
      value: 'Marco Paulo Ollivier'

  #Docker
  - name: ensure repository key is installed
    apt_key:
      id: "58118E89F3A912897C070ADBF76221572C52609D"
      keyserver: "hkp://p80.pool.sks-keyservers.net:80"
      state: present

  - name: ensure docker registry is available
    apt_repository:
      repo: 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
      state: present

  - name: ensure docker and dependencies are installed
    apt:
      name: docker-engine
      update_cache: yes

  - service:
      name: docker
      state: restarted

  - name: Installing packages
    apt:
      name: python-setuptools

  - name: Installing pip
    apt:
      name: python-pip
      state: latest

  - name: Installing Docker
    pip:
     name: docker

  - name: Installing docker compose
    pip:
     name: docker-compose

  - name: Installing dependencies docker compose
    pip:
     name: backports.ssl_match_hostname
     extra_args: --upgrade

  - name: Installing Docker-py
    command: pip install docker-py --upgrade

  - name: enable docker
    command: service docker restart

  - name: Installing CTOP
    command: sudo wget https://github.com/bcicen/ctop/releases/download/v0.5/ctop-0.5-linux-amd64 -O /usr/local/bin/ctop

  - name: Set permission for CTOP
    command: sudo chmod +x /usr/local/bin/ctop

  - name: Adding VivoControle team user to group docker
    command: useradd -G "{{ item.group }}" "{{ item.user}}"
    with_items:
      - { group: 'docker', user: 'mollivier' }
