###
---
- hosts: localhost
  become: yes
  become_method: sudo  
  gather_facts: yes
  tasks:

  - name: Install Dropbox
    apt:
      name: nautilus-dropbox
      state: latest
      update_cache: yes