###
---
- hosts: localhost
  sudo: yes
  tasks:

  - name: Install Vim
    apt:
      name: vim
      state: latest
      update_cache: yes

  - name: Install XClip
    apt:
      name: xclip
      state: latest
      update_cache: yes

  - name: Install ZSH
    apt:
      name: zsh
      state: latest
      update_cache: yes