###
---
- hosts: localhost
  become: yes
  become_method: sudo  
  gather_facts: yes
  tasks:

  #Git
  - name: Install Git
    apt:
      name: git
      state: latest
      update_cache: yes

  - git_config:
      name: user.email
      value: marcopollivier@gmail.com

  - git_config:
      name: user.name
      value: 'Marco Paulo Ollivier'
