###
---
- hosts: localhost
  become: yes
  become_method: sudo  
  gather_facts: yes
  tasks:

  - name: Install Stellarium
    apt:
      name: stellarium
      state: latest
      update_cache: yes
