###
---
- hosts: localhost
  become: yes
  become_method: sudo  
  gather_facts: yes
  tasks:

  - name: Install Terminator (terminal)
    apt:
      name: terminator
      state: latest
      update_cache: yes

  - name: Install Teamviewer
    apt:
      name: teamviewer
      state: latest
      update_cache: yes

  - name: Install Filezilla
    apt:
      name: filezilla
      state: latest
      update_cache: yes

  - name: Install Wireshark
    apt:
      name: wireshark
      state: latest
      update_cache: yes

  - name: Install Sublime
    apt:
      name: sublime-text
      state: latest
      update_cache: yes