---
- name: "Valida se release foi definida"
  fail: msg="Release deve ser informado"
  when: (var_deploy_release is not defined)

- debug: msg="Executando instalacao e configuracao de ambiente no release {{var_deploy_release}}"

- name: "Include common tasks"
  include: "common/main.yml"

- name: "Include update cache execution"
  include: "{{var_deploy_release}}/update-cache.yml"

- name: "Include basic installation"
  include: "{{var_deploy_release}}/basic.yml"

- name: "Include tools installation"
  include: "{{var_deploy_release}}/tools.yml"
  when: varfile_install_tools

- name: "Include study installation"
  include: "{{var_deploy_release}}/study.yml"
  when: varfile_install_study


# - include: ../../discord-notify/task/main.yml
#   vars:
#     text: "Deploy Realizado - {{ var_environment }}"
#     app: "{{ var_artifactname.split('-war')[0].replace('-',' ') }}"
#     image: "{{ var_version }}"
#     ambiente: "{{ var_environment }}"
